name: pre-deploy-check
# This workflow represents a set of basic End-to-End tests
on:
  push:
    branches:
      - 'master'
  # pull_request:
  # workflow_dispatch:

jobs:
  yaml-linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install yamllint
        run: pip install yamllint

      - name: Lint YAML files
        run: yamllint yamls/

  pluto-check:
    name: 'deprecated checks'
    runs-on: ubuntu-20.04
    needs: yaml-linting
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Pluto
        uses: FairwindsOps/pluto/github-action@master

      - name: Use pluto
        run: |
          pluto detect-files -d yamls/

  kustomize-check:
    needs: pluto-check
    name: 'Kustomize'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Kustomize Build'
        uses: karancode/kustomize-github-action@master
        with:
          kustomize_version: '3.0.0'
          kustomize_build_dir: '.'
          

  
